default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: startup_development
  username: test3
  password: test3
  port: 5432
  host: localhost

test:
  <<: *default
  database: startup_test
  username: test3
  password: test3
  port: 5432
  host: localhost
production:
  <<: *default
  database: startup_production
  url: <%= ENV["MY_APP_DATABASE_URL"] %>